spring:
  messages:
    basename: i18n.messages

  data:
    mongodb:
      host: ds361488.mlab.com
      database: heroku_tjwv260g
      username: user
      password: Aa123456
      uri: mongodb://user:Aa123456@ds361488.mlab.com:61488/heroku_tjwv260g?retryWrites=false