DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS(ID BIGINT auto_increment PRIMARY KEY, FIRSTNAME VARCHAR(255), LASTNAME VARCHAR(255));

DROP TABLE IF EXISTS GENRES;
CREATE TABLE GENRES(ID BIGINT auto_increment PRIMARY KEY, GENRENAME VARCHAR(255));

DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS(ID BIGINT auto_increment PRIMARY KEY, AUTHORID BIGINT, GENREID BIGINT, TITLE VARCHAR(255));