DROP TABLE IF EXISTS AUTHOR;
CREATE TABLE AUTHOR(ID BIGINT auto_increment PRIMARY KEY, FIRSTNAME VARCHAR(255), LASTNAME VARCHAR(255));

DROP TABLE IF EXISTS GENRE;
CREATE TABLE GENRE(ID BIGINT auto_increment PRIMARY KEY, GENRENAME VARCHAR(255));

DROP TABLE IF EXISTS BOOK;
CREATE TABLE BOOK(ID BIGINT auto_increment PRIMARY KEY, AUTHORID BIGINT, GENREID BIGINT, TITLE VARCHAR(255));