DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS(ID LONG PRIMARY KEY, FIRSTNAME VARCHAR(255), LASTNAME VARCHAR(255));

DROP TABLE IF EXISTS GENRES;
CREATE TABLE GENRES(ID LONG PRIMARY KEY, GENRENAME VARCHAR(255));